### ISSUE TITLE
Hint `A_t` in SCC

### ISSUE THREAD

**Issue by sigeisler** [deepmind/clrs#102]
Hi,

thank you for the quite extensive work in putting CLRS together.

Do you have a reference or reasoning about what `hints` you included? For example, can you elaborate on why you included hint `A_t` in strongly connected components?

Thanks!

**Comment by PetarV-** [comment]
Hi Simon,

Thank you for your continued interest in CLRS!

The hints were generally chosen to follow the pseudocode variables from the textbook. That being said, on occasion we inserted additional hints when we felt it would be beneficial for the network to make advantage of them.

In the case of A_t, we found it might be a good idea to make the model aware of the reversed graph, because in the second phase of Kosaraju's SCC algorithm it is necessary to do DFS over the reversed graph. But in principle this hint is not strictly necessary.

I hope this is helpful.

Thanks,
Petar

**Comment by sigeisler** [comment]
Hi Petar,

thanks for the explanation!

Best,
Simon
